.TH AEVOL "1" "August 2013" "aevol 4.1" "User Manual"
.SH NAME
aevol \- an in silico experimental evolution platform
.SH SYNOPSIS
.B aevol_run_X11 \-h
|
.B \-\-help
.br
.B aevol_run_X11 \-V
|
.B \-\-version
.br
.B aevol_run_X11 \fR[\fB\-r\fI GENERATION\fR] \fR[\fB\-n\fI NB_GENER\fR] \fR[\fB\-tvwx\fR]
.SH DESCRIPTION
.B Aevol
is a simulation platform that allows to let populations of digital organisms evolve in different conditions and study experimentally the mechanisms responsible for the structuration of the genome and the transcriptome.
.TP
.B aevol_run, aevol_run_X11
run an aevol simulation.
.SH OPTIONS
.TP
.B \-h, \-\-help
print this help, then exit
.TP
.B \-V, \-\-version
print version number, then exit
.HP
.B \-n, \-\-nbgener
.I NB_GENER
.br
number of generations to be run
.HP
.B \-r, \-\-resume
.I  GENERATION
.br
resume simulation at given generation
.TP
.B \-t, \-\-text
use text files instead of binary files when possible
.TP
.B \-v, \-\-verbose
be verbose
.TP
.B \-w, \-\-wait
pause after loading
.TP
.B \-x, \-\-noX
don't display X outputs upon start
.br
send SIGUSR1 to switch X output on/off
.SH "SEE ALSO"
.B aevol_create, aevol_modify, aevol_propagate
