./"test with man -l <file>
.TH AEVOL "1" "June 2016" "aevol 5.0 beta8" "User Manual"
.SH NAME
Aevol \- an in silico experimental evolution platform
.SH SYNOPSIS
.B aevol_misc_lineage \-h
|
.B \-\-help
.br
.B aevol_misc_lineage \-V
|
.B \-\-version
.br
.B aevol_misc_lineage \fR[\fB\-b\fI TIMESTEP\fR] \fR[\fB\-e\fI TIMESTEP\fR] \fR[\fB\-I\fI INDEX\fR | \fB\-R\fI RANK\fR] \fR[\fB\-F\fR] \fR[\fB\-v\fR]
.SH DESCRIPTION
.B Aevol
is a simulation platform that allows one to let populations of digital organisms evolve in different conditions and study experimentally the mechanisms responsible for the structuration of the genome and the transcriptome.
.TP
.B aevol_misc_lineage
reconstruct the lineage of a given individual from the tree files
.SH OPTIONS
.TP
.B \-h, \-\-help
print help, then exit
.TP
.B \-V, \-\-version
print version number, then exit
.HP
.B \-b, \-\-begin
.I  TIMESTEP
.br
specify time t0 up to which to reconstruct the lineage
.HP
.B \-e, \-\-end
.I  TIMESTEP
.br
specify time t_end of the indiv whose lineage is to be reconstructed
.HP
.B \-I, \-\-index
.I  INDEX
.br
specify the index of the indiv whose lineage is to be reconstructed
.HP
.B \-R, \-\-rank
.I  RANK
.br
specify the rank of the indiv whose lineage is to be reconstructed
default: best individual
.HP
.B \-F, \-\-full-check
.br
perform genome checks whenever possible
.HP
.B \-v, \-\-verbose
.br
be verbose
.SH "SEE ALSO"
.B aevol_create, aevol_modify, aevol_propagate, aevol_run
